### ISSUE TITLE
Got a huge error code. 

### ISSUE THREAD

**Issue by michaelkanrs** [Lunat1q/Catchem-PoGo#1062]
> (ERROR) System.ArgumentOutOfRangeException: Argument must be in range of -90 to 90
Parameter name: Latitude
   at GeoCoordinatePortable.GeoCoordinate.set_Latitude(Double value) in C:\projects\geocoordinate\src\GeoCoordinatePortable\GeoCoordinate.cs:line 109
   at PoGo.PokeMobBot.Logic.Utils.LocationUtils.CalculateDistanceInMeters(Double sourceLat, Double sourceLng, Double destLat, Double destLng) in D:\Catchem-PoGo\PoGo.PokeMobBot.Logic\Utils\LocationUtils.cs:line 16
   at PoGo.PokeMobBot.Logic.MapCache.<>c__DisplayClass9_0.<UpdateMapDatas>b__5(FortData i) in D:\Catchem-PoGo\PoGo.PokeMobBot.Logic\MapCache.cs:line 69
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at PoGo.PokeMobBot.Logic.MapCache.<UpdateMapDatas>d__9.MoveNext() in D:\Catchem-PoGo\PoGo.PokeMobBot.Logic\MapCache.cs:line 91
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.PokeMobBot.Logic.State.InfoState.<Execute>d__0.MoveNext() in D:\Catchem-PoGo\PoGo.PokeMobBot.Logic\State\InfoState.cs:line 21
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.PokeMobBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in D:\Catchem-PoGo\PoGo.PokeMobBot.Logic\State\StateMachine.cs:line 39

I am confused. What does this mean? How do I fix it?

**Comment by sapdkeybinder** [comment]
please post your Latitude and Longitude what do you use

Problem: Argument must be in range of -90 to 90
Parameter name: Latitude

Check this
