### ISSUE TITLE
Login issues (PLEASE HELP)

### ISSUE THREAD

**Issue by leifpile** [Lunat1q/Catchem-PoGo#1150]
The very first time I opened catchem it was working perfectly fine aside from the map and when I closed it and returned 2 hours later my profile was gonna so I put in the login credentials as they were 2 hours ago and it comes up with an error.

**Comment by goiabs** [comment]
Maybe you got a ban.

**Comment by leifpile** [comment]
I didn't because I just logged into the account

**Comment by wagas** [comment]
do you have a ps?

**Comment by leifpile** [comment]
I'm sorry can you please explain what a ps is please I am very naïve when it comes to this type of stuff

**Comment by wagas** [comment]
printscreen

**Comment by Lunat1q** [comment]
no info provided

**Comment by WsTs** [comment]
restart your modem should fix the issue, maybe there are few devices using same ip, i had been running 12 hours non-stop and it is fine

**Comment by magicdev2** [comment]
or erase the bot and reinstall it

**Comment by vmwiz** [comment]
Which type of account? Google or PTC? I had this issue because I hadn't confirmed my PTC account by clicking on the link they sent by email. After confirmed the account, my PTC account was usable again.

**Comment by leifpile** [comment]
It is a ptc account that has it's email confirmed

**Comment by leifpile** [comment]
Whenever I try to log in this message pops up:

[08:05:19] (ERROR) System.ArgumentNullException: Value cannot be null.
Parameter name: ptr
   at System.Runtime.InteropServices.Marshal.GetDelegateForFunctionPointer(IntPtr ptr, Type t)
   at PokemonGo.RocketAPI.Helpers.RequestBuilder.FunctionLoader.LoadFunction[T](String dllPath, String functionName) in D:\Ketchum\Catchem-PoGo\PokemonGoAPI\PokemonGo.RocketAPI\Helpers\RequestBuilder.cs:line 232
   at PokemonGo.RocketAPI.Helpers.RequestBuilder..ctor(String authToken, AuthType authType, Double latitude, Double longitude, Double altitude, ISettings settings, AuthTicket authTicket) in D:\Ketchum\Catchem-PoGo\PokemonGoAPI\PokemonGo.RocketAPI\Helpers\RequestBuilder.cs:line 58
   at PokemonGo.RocketAPI.Rpc.BaseRpc.get_RequestBuilder() in D:\Ketchum\Catchem-PoGo\PokemonGoAPI\PokemonGo.RocketAPI\Rpc\BaseRpc.cs:line 17
   at PokemonGo.RocketAPI.Rpc.Login.<SetServer>d__4.MoveNext() in D:\Ketchum\Catchem-PoGo\PokemonGoAPI\PokemonGo.RocketAPI\Rpc\Login.cs:line 69
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__3.MoveNext() in D:\Ketchum\Catchem-PoGo\PokemonGoAPI\PokemonGo.RocketAPI\Rpc\Login.cs:line 55
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.PokeMobBot.Logic.State.LoginState.<Execute>d__0.MoveNext() in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\State\LoginState.cs:line 3

**Comment by leifpile** [comment]
i found out the problem, it was because i was missing the mapzen elevation key
