### ISSUE TITLE
Sniping is working ?

### ISSUE THREAD

**Issue by Gnacik** [Lunat1q/Catchem-PoGo#1265]
No idea if sniping is working in CatchEm ? I know that in config tab there is no sniping options, but in config still present. When enabled it throws error:

```
[13:37:19] (ERROR) System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at PoGo.PokeMobBot.Logic.Tasks.SnipePokemonTask.<Start>d__10.MoveNext() in C:\dev\Catchem-PoGo\PoGo.PokeMobBot.Logic\Tasks\SnipePokemonTask.cs:line 612
```

**Comment by Krypsus** [comment]
Snipe = ban #1155
