### ISSUE TITLE
I tried 3 different Computers and still doesn't let me bot Pokemon Go.

### ISSUE THREAD

**Issue by R6rick** [Lunat1q/Catchem-PoGo#1414]
[20:07:47] (ERROR) System.ArgumentNullException: Value cannot be null.
Parameter name: ptr
   at System.Runtime.InteropServices.Marshal.GetDelegateForFunctionPointer(IntPtr ptr, Type t)
   at PokemonGo.RocketAPI.Helpers.RequestBuilder.FunctionLoader.LoadFunction[T](String dllPath, String functionName) in D:\Catchem\PoGoAPI\PoGo.RocketAPI\Helpers\RequestBuilder.cs:line 245
   at PokemonGo.RocketAPI.Helpers.RequestBuilder..ctor(String authToken, AuthType authType, Double latitude, Double longitude, Double altitude, ISettings settings, AuthTicket authTicket) in D:\Catchem\PoGoAPI\PoGo.RocketAPI\Helpers\RequestBuilder.cs:line 71
   at PokemonGo.RocketAPI.Rpc.BaseRpc.get_RequestBuilder() in D:\Catchem\PoGoAPI\PoGo.RocketAPI\Rpc\BaseRpc.cs:line 15
   at PokemonGo.RocketAPI.Rpc.Login.<SetServer>d__4.MoveNext() in D:\Catchem\PoGoAPI\PoGo.RocketAPI\Rpc\Login.cs:line 70
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__3.MoveNext() in D:\Catchem\PoGoAPI\PoGo.RocketAPI\Rpc\Login.cs:line 56
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.PokeMobBot.Logic.State.LoginState.<Execute>d__0.MoveNext() in D:\Catchem\PoGo.PokeMobBot.Logic\State\LoginState.cs:line 33

**Comment by R6rick** [comment]
It was working before until my computer restarted for an update

**Comment by R6rick** [comment]
Fine then Ill use a different Pokemon Go bot >:(

**Comment by druds** [comment]
no one works for you here!
stop to cry like a babe and wait until someone help you, iff they want to


try to reeintall bot

**Comment by R6rick** [comment]
It's midnight and I wanna go to sleep. Also I reinstalled it many times and I still didn't work.
I need this thing to work at midnight bro

**Comment by Spk345** [comment]
Have you Updated to RELEASE 1.5.0?

**Comment by Spk345** [comment]
Also, no one here is paid to help you. You can choose to support Lunatiq and his awesome coding skills, but the rest of us do not get paid. We just want to lessen the load for Lunatiq. That is all.
