### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by JacksonTrue** [Lunat1q/Catchem-PoGo#143]
As requested , the logs from Windows Journal .

Контейнер ошибки 343871307, тип 30
Имя события: CLR20r3
Ответ: Нет данных
Идентификатор CAB: 0

Сигнатура проблемы:
P1: Catchem.exe
P2: 1.3.5.0
P3: 57b36fd7
P4: Catchem
P5: 1.3.5.0
P6: 57b36fd7
P7: 205
P8: 0
P9: System.NullReferenceException
P10: 

Вложенные файлы:
C:\Users\User\AppData\Local\Temp\WER7695.tmp.WERInternalMetadata.xml
C:\Users\User\AppData\Local\Temp\WER8259.tmp.appcompat.txt
C:\Users\User\AppData\Local\Temp\WER8289.tmp.mdmp

Эти файлы можно найти здесь:
C:\Users\User\AppData\Local\Microsoft\Windows\WER\ReportArchive\AppCrash_Catchem.exe_65f811b08f2b346bc5c1efd4d11eca72df7119c3_34229397

Символ анализа: 
Повторный поиск решения: 0
Идентификатор отчета: 03176301-63ed-11e6-a191-005056c00008
Состояние отчета: 9

Имя сбойного приложения: Catchem.exe, версия: 1.3.5.0, отметка времени: 0x57b36fd7
Имя сбойного модуля: KERNELBASE.dll, версия: 6.1.7601.18409, отметка времени 0x53159a86
Код исключения: 0xe0434352
Смещение ошибки: 0x0000c42d
Идентификатор сбойного процесса: 0xef88
Время запуска сбойного приложения: 0x01d1f7f9b84da6e2
Путь сбойного приложения: C:\Users\User\Desktop\Вторая партия\Catchem\Catchem.exe
Путь сбойного модуля: C:\Windows\syswow64\KERNELBASE.dll
Код отчета: 03176301-63ed-11e6-a191-005056c00008

Application: Catchem.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
Stack:
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at System.Windows.Application.Run(System.Windows.Window)
   at Catchem.App.Main()

**Comment by JacksonTrue** [comment]
Контейнер ошибки 343869312, тип 30
Имя события: CLR20r3
Ответ: Нет данных
Идентификатор CAB: 0

Сигнатура проблемы:
P1: Catchem.exe
P2: 1.3.5.0
P3: 57b36fd7
P4: System
P5: 4.0.30319.34238
P6: 53e450ed
P7: 13a0
P8: 5b
P9: System.ArgumentException
P10: 

Вложенные файлы:
C:\Users\User\AppData\Local\Temp\WER24DD.tmp.WERInternalMetadata.xml
C:\Users\User\AppData\Local\Temp\WER3091.tmp.appcompat.txt
C:\Users\User\AppData\Local\Temp\WER30E0.tmp.mdmp

Эти файлы можно найти здесь:
C:\Users\User\AppData\Local\Microsoft\Windows\WER\ReportArchive\AppCrash_Catchem.exe_367abdbf0ac739fb2c78ecbce935e386b8c988_2fa4e790

Символ анализа: 
Повторный поиск решения: 0
Идентификатор отчета: a880935e-63ec-11e6-a191-005056c00008
Состояние отчета: 9



Имя сбойного приложения: Catchem.exe, версия: 1.3.5.0, отметка времени: 0x57b36fd7
Имя сбойного модуля: KERNELBASE.dll, версия: 6.1.7601.18409, отметка времени 0x53159a86
Код исключения: 0xe0434352
Смещение ошибки: 0x0000c42d
Идентификатор сбойного процесса: 0x14404
Время запуска сбойного приложения: 0x01d1f7f963693b71
Путь сбойного приложения: C:\Users\User\Desktop\Вторая партия\Catchem\Catchem.exe
Путь сбойного модуля: C:\Windows\syswow64\KERNELBASE.dll
Код отчета: a880935e-63ec-11e6-a191-005056c00008


Application: Catchem.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException
Stack:
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__5(System.Object)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by Lunat1q** [comment]
ok. проверю.
Конфиги новые? или со старых версий ставил? Если так то попробуй новые.

**Comment by JacksonTrue** [comment]
Я просто перезаливаю с архива в папку с прошлой версии, где у меня готовые конфиги. Также я слежу за фиксами и сразу корректирую настройки. Т.е мин макс скорость добавил, также настройки тайм аута итп. Но данная проблема присутствовала даже когда я чистую версию запускал и заново настраивал конфиги.
________________________________________________________________________________________________
I just upload a file to a folder with the previous version, where I finished configs. Also, I am following fixes and immediately corrective nastroyki.T.e min max speed is added also the timeout settings. But the problem is present even when I ran a clean and re-set up the configs.

**Comment by Lunat1q** [comment]
Напиши в дискорде, я тебе скину дебаг версию.

**Comment by JacksonTrue** [comment]
Я не знаю, что такое дискорд, недавно не гитхабе зарегистрировался. Напиши мне на Skype: whiteskype7777
