### ISSUE TITLE
another runtime error

### ISSUE THREAD

**Issue by Cowering** [Lunat1q/Catchem-PoGo#1476]
I checked, I do have latest .net framework. I rebooted the machine (win7 64 bit) and loading catchem now gives this when i click to 'map&console' to set a new starting location:  I'll try again, but when the bot last crashed, it was in the middle of running something as a schedule. Maybe some flag didn't get cleared on restart??

![capture5](https://cloud.githubusercontent.com/assets/9252175/18276795/7a29dde6-7409-11e6-82d9-eecaf7401d0b.PNG)

(the text)

[08:05:30] (ERROR) PokemonGo.RocketAPI.Exceptions.InvalidResponseException: Exception of type 'PokemonGo.RocketAPI.Exceptions.InvalidResponseException' was thrown.
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__1`2.MoveNext() in D:\catchem\PoGoAPI\PoGo.RocketAPI\Extensions\HttpClientExtensions.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__7`2.MoveNext() in D:\catchem\PoGoAPI\PoGo.RocketAPI\Rpc\BaseRpc.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Player.<GetPlayer>d__4.MoveNext() in D:\catchem\PoGoAPI\PoGo.RocketAPI\Rpc\Player.cs:line 53
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.PokeMobBot.Logic.State.LoginState.<DownloadProfile>d__2.MoveNext() in D:\catchem\PoGo.PokeMobBot.Logic\State\LoginState.cs:line 259
[08:05:30] (ATTENTION) Current Operation was canceled. Bot stopped/paused.

**Comment by Cowering** [comment]
the previous was the final output on the console.. for a few seconds on a startup, it says this (I don't proxy!)

[08:13:26] (INFO) Proxy Down? Will try to interact with server anyway
[08:13:26] (UPDATE) Perfect! You already have the newest Version 
[08:13:26] (INFO) Logging in using account Ptc
[08:13:29] (ERROR) System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: An attempt was made to access a socket in a way forbidden by its access permissions 174.35.22.153:443
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Login.PtcLogin.<GetSessionCookie>d__9.MoveNext() in D:\catchem\PoGoAPI\PoGo.RocketAPI\Login\PtcLogin.cs:line 94
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Login.PtcLogin.<GetAccessToken>d__4.MoveNext() in D:\catchem\PoGoAPI\PoGo.RocketAPI\Login\PtcLogin.cs:line 35
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__3.MoveNext() in D:\catchem\PoGoAPI\PoGo.RocketAPI\Rpc\Login.cs:line 55
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.PokeMobBot.Logic.State.LoginState.<Execute>d__0.MoveNext() in D:\catchem\PoGo.PokeMobBot.Logic\State\LoginState.cs:line 33
[08:13:29] (INFO) Trying again in 45 seconds...

**Comment by Cowering** [comment]
oh hell. ignore this one.  Apparently enough changed between 1.5.0.0 and newest update to trigger my firewall into thinking it had become a virus, blocking it
