### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by EnzzoCaaue** [Lunat1q/Catchem-PoGo#154]
```
[23:20:02] (ERROR) System.ArgumentNullException: Value can not be null.
Parameter name: source
   in System.Linq.Enumerable.Any [TSource] (IEnumerable`1 source, Func`2 predicate)
   . In PoGo.PokeMobBot.Logic.Tasks.CatchWildPokemonsTask <MoveToPokemon> d__1.MoveNext () in D: \ Ketchum \ Catchem-PoGo \ PoGo.PokeMobBot.Logic \ Tasks \ CatchWildPokemonsTask.cs: line 0
--- End of the stack trace of the previous location where the exception was generated ---
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (Task task)
   in PoGo.PokeMobBot.Logic.Tasks.CatchWildPokemonsTask <Run> d__0.MoveNext () in D:. \ Ketchum \ Catchem-PoGo \ PoGo.PokeMobBot.Logic \ Tasks \ CatchWildPokemonsTask.cs: line 38
--- End of the stack trace of the previous location where the exception was generated ---
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (Task task)
   in PoGo.PokeMobBot.Logic.Tasks.FarmPokeStopsDiscoveryTask <Run> d__1.MoveNext () in D:. \ Ketchum \ Catchem-PoGo \ PoGo.PokeMobBot.Logic \ Tasks \ FarmPokestopsDiscoveryTask.cs: line 159
--- End of the stack trace of the previous location where the exception was generated ---
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (Task task)
   in PoGo.PokeMobBot.Logic.State.FarmState <Run> d__0.MoveNext () in D:. \ Ketchum \ Catchem-PoGo \ PoGo.PokeMobBot.Logic \ State \ FarmState.cs: line 54
--- End of the stack trace of the previous location where the exception was generated ---
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (Task task)
   in PoGo.PokeMobBot.Logic.State.StateMachine <Start> d__3.MoveNext () in D:. \ Ketchum \ Catchem-PoGo \ PoGo.PokeMobBot.Logic \ State \ StateMachine.cs: line 38
[23:22:22] (INFO) Logging in using account Ptc
```

I got theses errors like every minute then bot restarts.

**Comment by xTeddiusx** [comment]
same errors here

**Comment by Reynico7** [comment]
getting this error, its my first time using it so I'm sorry if I did anything wrong, and also I know nothing about programming so please go easy on me. also I signed up for GitHub just to comment this

[23:30:51] (ERROR) System.ArgumentNullException: Value cannot be null.
Parameter name: message
   at Google.Protobuf.ProtoPreconditions.CheckNotNull[T](T value, String name)
   at Google.Protobuf.MessageExtensions.ToByteArray(IMessage message)
   at PokemonGo.RocketAPI.Helpers.RequestBuilder.GenerateSignature(IEnumerable`1 requests) in D:\Ketchum\Catchem-PoGo\PokemonGoAPI\PokemonGo.RocketAPI\Helpers\RequestBuilder.cs:line 115
   at PokemonGo.RocketAPI.Helpers.RequestBuilder.GetRequestEnvelope(Request[] customRequests) in D:\Ketchum\Catchem-PoGo\PokemonGoAPI\PokemonGo.RocketAPI\Helpers\RequestBuilder.cs:line 211
   at PokemonGo.RocketAPI.Helpers.RequestBuilder.GetRequestEnvelope(RequestType type, IMessage message) in D:\Ketchum\Catchem-PoGo\PokemonGoAPI\PokemonGo.RocketAPI\Helpers\RequestBuilder.cs:line 260
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__6`2.MoveNext() in D:\Ketchum\Catchem-PoGo\PokemonGoAPI\PokemonGo.RocketAPI\Rpc\BaseRpc.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Player.<GetPlayer>d__3.MoveNext() in D:\Ketchum\Catchem-PoGo\PokemonGoAPI\PokemonGo.RocketAPI\Rpc\Player.cs:line 52
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.PokeMobBot.Logic.State.LoginState.<DownloadProfile>d__2.MoveNext() in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\State\LoginState.cs:line 181
[23:30:51] (ERROR) Current Operation was canceled.
