### ISSUE TITLE
Am i banned ? 

### ISSUE THREAD

**Issue by 3xPNOY** [Lunat1q/Catchem-PoGo#1569]
I cannot login to my first account. 
My second works fine. 
I have never teleport me somewhere!

PTC login failed. Make sure you have entered the right Email & Password. If you continue to get this, check your phone or Nox for a ban. Exiting...
[18:15:09] (ERROR) PokemonGo.RocketAPI.Exceptions.InvalidResponseException: Exception of type 'PokemonGo.RocketAPI.Exceptions.InvalidResponseException' was thrown.
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__1`2.MoveNext() in C:\dev\Catchem\PoGoAPI\PoGo.RocketAPI\Extensions\HttpClientExtensions.cs:line 79
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__7`2.MoveNext() in C:\dev\Catchem\PoGoAPI\PoGo.RocketAPI\Rpc\BaseRpc.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Player.<GetPlayer>d__4.MoveNext() in C:\dev\Catchem\PoGoAPI\PoGo.RocketAPI\Rpc\Player.cs:line 53
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.PokeMobBot.Logic.State.LoginState.<DownloadProfile>d__2.MoveNext() in C:\dev\Catchem\PoGo.PokeMobBot.Logic\State\LoginState.cs:line 259

**Comment by EllosGaming** [comment]
Did u tried to login on this account on a smartphone or nox app player? See what happens.

**Comment by 3xPNOY** [comment]
When i log in into nox with my account then i spawn in germany, but the bot are running in NY.

**Comment by 3xPNOY** [comment]
I will be banned then. Sorry for my english by the way haha

**Comment by EllosGaming** [comment]
Logoff the bot for 24 hours and then try on nox. Or just change the nox gps location to NY.

**Comment by 3xPNOY** [comment]
how do i do that ? :l

**Comment by EllosGaming** [comment]
Wait a sec, I'll print it for you.

**Comment by 3xPNOY** [comment]
ok thank you!

**Comment by EllosGaming** [comment]
![gpslocation](https://cloud.githubusercontent.com/assets/22061672/18357752/830482e8-75c8-11e6-8683-c691545beb61.PNG)
Look this icon on circle. Click on it and select on the map.
