### ISSUE TITLE
HELP!!

### ISSUE THREAD

**Issue by cheeming123** [Lunat1q/Catchem-PoGo#1706]
Please help me fix this...i am new

[10:30:57] (UPDATE) Perfect! You already have the newest Version 1.5.2.1
[10:30:57] (INFO) Logging in using account Ptc
[10:30:59] (ERROR) System.ArgumentNullException: Value cannot be null.
Parameter name: ptr
   at System.Runtime.InteropServices.Marshal.GetDelegateForFunctionPointer(IntPtr ptr, Type t)
   at PokemonGo.RocketAPI.Helpers.RequestBuilder.FunctionLoader.LoadFunction[T](String dllPath, String functionName) in D:\catchem\PoGoAPI\PoGo.RocketAPI\Helpers\RequestBuilder.cs:line 245
   at PokemonGo.RocketAPI.Helpers.RequestBuilder..ctor(String authToken, AuthType authType, Double latitude, Double longitude, Double altitude, ISettings settings, AuthTicket authTicket) in D:\catchem\PoGoAPI\PoGo.RocketAPI\Helpers\RequestBuilder.cs:line 71
   at PokemonGo.RocketAPI.Rpc.BaseRpc.get_RequestBuilder() in D:\catchem\PoGoAPI\PoGo.RocketAPI\Rpc\BaseRpc.cs:line 15
   at PokemonGo.RocketAPI.Rpc.Login.<SetServer>d__4.MoveNext() in D:\catchem\PoGoAPI\PoGo.RocketAPI\Rpc\Login.cs:line 70
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__3.MoveNext() in D:\catchem\PoGoAPI\PoGo.RocketAPI\Rpc\Login.cs:line 56
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.PokeMobBot.Logic.State.LoginState.<Execute>d__0.MoveNext() in D:\catchem\PoGo.PokeMobBot.Logic\State\LoginState.cs:line 33

**Comment by alanearl** [comment]
Check username & password?

**Comment by cheeming123** [comment]
Username &password is correct...

**Comment by Spk345** [comment]
Check your account through either phone or ptc website. If you are certain your log in credentials are correct in the auth.txt, then you may have been banned.
