### ISSUE TITLE
[ERROR] Error in Windows 10 1607 x64

### ISSUE THREAD

**Issue by Enfurecido** [Lunat1q/Catchem-PoGo#1736]
The error occurs after a few minutes of use, it simply closes. "An error occurred and the application will be closed"

It does not have any code.

I use Windows 10 Enterprise x64, v.1607

**Comment by Spk345** [comment]
Post a screenshot of your Windows Event Log, and we'll see what crashed.

**Comment by Spk345** [comment]
Was there any error that triggered it last in your catchem logs?

**Comment by mizriel** [comment]
Having same issue, windows 10 enterprise x64. Below are the event logs, hope it help

Application: Catchem.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException
   at System.ThrowHelper.ThrowInvalidOperationException(System.ExceptionResource)
   at System.Collections.Generic.List`1+Enumerator[[GMap.NET.PointLatLng, GMap.NET.Core, Version=1.7.0.0, Culture=neutral, PublicKeyToken=b85b9027b614afef]].MoveNextRare()
   at System.Collections.Generic.List`1+Enumerator[[GMap.NET.PointLatLng, GMap.NET.Core, Version=1.7.0.0, Culture=neutral, PublicKeyToken=b85b9027b614afef]].MoveNext()
   at GMap.NET.WindowsPresentation.GMapRoute.RegenerateShape(GMap.NET.WindowsPresentation.GMapControl)
   at GMap.NET.WindowsPresentation.GMapControl.ForceUpdateOverlays()
   at Catchem.Pages.MapPage+<MovePlayer>d__27.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at System.Windows.Application.Run(System.Windows.Window)
   at Catchem.App.Main()

Faulting application name: Catchem.exe, version: 1.5.3.0, time stamp: 0x57d59d42
Faulting module name: KERNELBASE.dll, version: 10.0.14393.0, time stamp: 0x57898e34
Exception code: 0xe0434352
Fault offset: 0x000d96c2
Faulting process id: 0xcc
Faulting application start time: 0x01d20d5a6040df7d
Faulting application path: C:\Users\Sambal Lab\Downloads\Catchem 1.1\Catchem.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 6cb72d8e-a21e-4406-be2f-631fda015f37
Faulting package full name:

**Comment by rafaelcarsetimo** [comment]
Same issue here... Windows 8.1 x64, after the 1.5.x update.

**Comment by Spk345** [comment]
Thank you for the error log. That will be helpful. @Lunat1q

**Comment by mizriel** [comment]
should we downgradeit to previous version? the bot will only run for a while then error

**Comment by rafaelcarsetimo** [comment]
I just delete my ROUTEs created and no more force close happens. Just for info. Tks.

**Comment by rafaelcarsetimo** [comment]
Just for information... after detete the routes... the program work for hours... but after click to move to another area, the software crash. I believe that is a MAP problem, coordinates... just a clue... Thanks.

**Comment by Lunat1q** [comment]
Knows issue, fixed, not yet released
