### ISSUE TITLE
Error Issue and Some Feature Request

### ISSUE THREAD

**Issue by wynterz** [Lunat1q/Catchem-PoGo#178]
**Catch'em v1.3.5**

_Error Issue_
First of all, there is a problem on the Proxy setting. Whenever i press the "START" button. There will be a message show "(INFO) Proxy Down?" I've tried to run it for a few hours but still no luck. The bot just wont run and catch a pickachu for me. xDD
Note: I use the same proxy on V1.2.5 and there is no problem.

Next, after i logged in, sometime there is pokestop spawn around me but it will just say that there is no usable pokestop around me. This just happened occasionally, dont know what trigger it.

Recycle at usage percentage not working fine. it will max out my bag and continue to loot for around 5-10 minutes then only recycle.

Sometimes it will show the error as below, then login again. Happened occasionally with a period of 5~30 minute interval.
(ERROR) System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at PoGo.PokeMobBot.Logic.Tasks.CatchWildPokemonsTask.<MoveToPokemon>d__1.MoveNext() in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\Tasks\CatchWildPokemonsTask.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.PokeMobBot.Logic.Tasks.CatchWildPokemonsTask.<Execute>d__0.MoveNext() in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\Tasks\CatchWildPokemonsTask.cs:line 38
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.PokeMobBot.Logic.Tasks.FarmPokeStopsDiscoveryTask.<Execute>d__1.MoveNext() in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\Tasks\FarmPokestopsDiscoveryTask.cs:line 159
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.PokeMobBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\State\FarmState.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.PokeMobBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\State\StateMachine.cs:line 38

_Feature Request_
 - To be able to resize the application vertically.
 - To be able to favourite and rename pokemon maybe?
 - A checkbox to enable min duplicate pokemon (I set keep min Iv % to 90 and keep min duplicate to 1, then it transfer all the pokemon away and left 1 highest Iv pokemon only regardless of the pokemon is >90% Iv or not. Its quite sad when the pokemon >90% Iv got transferred away.)
 - Amount of Pokebals to keep can change to 3 different field Amount of pokeball, Amount of greatball, Amount of ultraball instead of grouping into 1?
 - a button to refresh pokemon and inventory or a timer maybe?
 
I think this should be all. Will continue to leave u suggestion if there is anything found to be improve. Thx for your bot btw. It really helps out a lot ;P

P/S: will buy u a pizza after i get my salary. hahaha :D

**Comment by kirimkefadil** [comment]
and add some features like
- color difference for lure pokestop
- double click forcemove to pokestop
- incense usage
- add human speed, bicycle speed, drive speed option maybe?

**Comment by wynterz** [comment]
**Additional bug**
just found out that the Min Altitude and Max Altitude not working. My altitude changed to 4681.89912 while i was botting. 

> I believe i can fly~ I believe i can touch the sky~ I dream about it night and day~ Spread my wings and fly away~

**Comment by Lunat1q** [comment]
bug should be fixed in 1.4.0.0
1. there sohuld be no problems with resize, but window name height and width min.
2. in future releases - yes
3.  check transfer cp and iv in 1.4.0.0
4. no, i see no point to keep low grade balls instead of high
5. i'm thinking about it, but still wanna do it redundant, in case of properly working auto updater.

--
6. lured pokestops are pink
7. not possible, cause pokestop id is being behind the scene, but in 1.4.0.0 while forcemove, bot will use ALL pokestops on the way
8. check roadmap in discord
9. sorry, no.

**Comment by wynterz** [comment]
@Lunat1q thx dude for ur fast respond... cant wait to see 1.4.0... btw great job dude... tq really much
