### ISSUE TITLE
[MOVE PLAYER FAILURE] in Catchem_1.5.3.0_build35_RC2

### ISSUE THREAD

**Issue by Pascal-m** [Lunat1q/Catchem-PoGo#1792]
Hello sometime i have this error in my log:

_[13:13:02] [MOVE PLAYER FAILURE] Collection was modified; enumeration operation may not execute. trace:    at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at GMap.NET.WindowsPresentation.GMapRoute.RegenerateShape(GMapControl map)
   at GMap.NET.WindowsPresentation.GMapControl.ForceUpdateOverlays()
   at Catchem.Pages.MapPage.<MovePlayer>d__25.MoveNext()_

**Comment by velwong** [comment]
I am struck at the login ..
Double Confirmed my login credentials are correct. 

Initializing Rocket logger at time 16/9/2016 12:51:47 AM...
[00:52:19] Your IP is: XX.XX.XX.XX
[00:52:19] Perfect! You already have the newest Version 1.5.2.1
[00:52:19] Logging in using account Ptc

**Comment by Pascal-m** [comment]
hello  velwong
plz,  should you open another issue from your post and remove it .
It is not related to my problem.
thk

**Comment by Spk345** [comment]
@Pascal-m
 The first error code is due to catchem not being able to find your location (it's a weird issue that's been plaguing us from rc17). The workaround, upon immediately starting your bot, just force move him any old place and that should stop that error from occurring.

@velwong
The second error is unstable Internet connection or login timeout (i.e. PTC or google login servers are having issues). In before you say that your other bot is working perfectly, all new players need to pass through login servers to enter game servers. If login servers go down, bots and players who already were player are *not* affected.
