### ISSUE TITLE
http proxy doesn't work

### ISSUE THREAD

**Issue by LisaChang35** [Lunat1q/Catchem-PoGo#1883]
Catchem Version: 1.5.3.0
I run two bots, one is my my home FTTH IP, another one I setup a Squid3 server 45.32.41.72:3128
When I checked on the "Use proxy", the console will soon show this:
```
[02:54:23] (ERROR) Google.Protobuf.InvalidProtocolBufferException: SkipLastField called on an end-group tag, indicating that the corresponding start-group was missing
   at Google.Protobuf.CodedInputStream.SkipLastField()
   at POGOProtos.Networking.Envelopes.ResponseEnvelope.MergeFrom(CodedInputStream input) in C:\dev\Catchem\POGOProtos\Networking\Envelopes\ResponseEnvelope.cs:line 283
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProto>d__2`1.MoveNext() in C:\dev\Catchem\PoGoAPI\PoGo.RocketAPI\Extensions\HttpClientExtensions.cs:line 119
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__1`2.MoveNext() in C:\dev\Catchem\PoGoAPI\PoGo.RocketAPI\Extensions\HttpClientExtensions.cs:line 65
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__7`2.MoveNext() in C:\dev\Catchem\PoGoAPI\PoGo.RocketAPI\Rpc\BaseRpc.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Player.<GetPlayer>d__4.MoveNext() in C:\dev\Catchem\PoGoAPI\PoGo.RocketAPI\Rpc\Player.cs:line 53
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.PokeMobBot.Logic.State.LoginState.<DownloadProfile>d__2.MoveNext() in C:\dev\Catchem\PoGo.PokeMobBot.Logic\State\LoginState.cs:line 259
[02:54:23] (ATTENTION) Current Operation was canceled. Bot stopped/paused.
```

**Comment by Spk345** [comment]
Did you try and test the proxy before you tried to use it? Did it say if it was valid or not?

**Comment by Spk345** [comment]
You need to use a proxy service that offers HTTPS and Socks5 protocol.
