### ISSUE TITLE
Proxy ?

### ISSUE THREAD

**Issue by supernutz** [Lunat1q/Catchem-PoGo#190]
Only happen when proxy enable.
[20:26:56] (INFO) Logging in using account Ptc
[20:26:56] (ERROR) System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Login.PtcLogin.<GetSessionCookie>d__9.MoveNext() in D:\Ketchum\Catchem-PoGo\PokemonGoAPI\PokemonGo.RocketAPI\Login\PtcLogin.cs:line 94
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Login.PtcLogin.<GetAccessToken>d__4.MoveNext() in D:\Ketchum\Catchem-PoGo\PokemonGoAPI\PokemonGo.RocketAPI\Login\PtcLogin.cs:line 35
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__3.MoveNext() in D:\Ketchum\Catchem-PoGo\PokemonGoAPI\PokemonGo.RocketAPI\Rpc\Login.cs:line 53
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.PokeMobBot.Logic.State.LoginState.<Execute>d__0.MoveNext() in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\State\LoginState.cs:line 32

**Comment by wynterz** [comment]
proxy still not working in v1.4.0... "(INFO) Proxy Down?" Error... the used proxy works fine in 1.2.5

**Comment by Lunat1q** [comment]
it works fine. 
But if you are behind corporate proxy - that can be an issue
