### ISSUE TITLE
a problem occur when I start bot after short pause

### ISSUE THREAD

**Issue by searchingDD** [Lunat1q/Catchem-PoGo#1957]
I start the bot after a short break (2 mins maybe) and changed some setting about transfer. Then I saw it after I restart the bot. I'm not sure what kind of problem and I can't find related issue about. Should I worry about this?
---------------------------------------------------------------
here's log:

System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at DankMemes.GPSOAuthSharp.GoogleKeyUtils.ParseAuthResponse(String text) in D:\catchem\GPSOAuthSharp\GPSOAuthSharp.cs:line 143
   at DankMemes.GPSOAuthSharp.GPSOAuthClient.PerformAuthRequest(Dictionary`2 data) in D:\catchem\GPSOAuthSharp\GPSOAuthSharp.cs:line 60
   at DankMemes.GPSOAuthSharp.GPSOAuthClient.PerformMasterLogin(String service, String deviceCountry, String operatorCountry, String lang, Int32 sdkVersion) in D:\catchem\GPSOAuthSharp\GPSOAuthSharp.cs:line 83
   at PokemonGo.RocketAPI.Login.GoogleLogin.<GetAccessToken>d__4.MoveNext() in D:\catchem\PoGoAPI\PoGo.RocketAPI\Login\GoogleLogin.cs:line 24
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__3.MoveNext() in D:\catchem\PoGoAPI\PoGo.RocketAPI\Rpc\Logi

**Comment by Spk345** [comment]
Are you using the current pre-release RC 54?

[![Newest Release](http://s9.postimg.org/exom179kf/Newes.png)](https://github.com/Lunat1q/Catchem-PoGo/releases)

**Comment by searchingDD** [comment]
I use 1.5.2.1 download from here.

**Comment by Spk345** [comment]
Version 1.5.2.1 has a lot of bugs, and misses a lot of the newer features 1.5.3. has. I recommend you upgrade to the Pre-release. It's the same great thing as 1.5.2.1. but we call it a Pre-Release because it doesn't use the newest Pokemon Go API. 

We will not help you on this issue, as there were so many bugs with 1.5.2.1.

#1960
