### ISSUE TITLE
[Issue] V1.5.3.0

### ISSUE THREAD

**Issue by voctavio** [Lunat1q/Catchem-PoGo#2059]
This just started happening a few mintues ago, I had no problem with my other bots in the same version. I Usually have found that it's the user name/password. 

[20:48:49] (INFO) Your IP is: 
[20:48:50] (UPDATE) Perfect! You already have the newest Version 1.5.2.1
[20:48:50] (INFO) Logging in using account Google
[20:48:50] (ATTENTION) Current Operation was canceled. Bot stopped/paused.
[20:48:51] (INFO) Playing as ******
[20:48:51] (ATTENTION) Make sure Lat & Lng are right. Exit Program if not! Lat: 22.2938742910819 Lng: 114.168717221042 Alt: 7.63063655278209
[20:48:58] (INFO) During that pause, consider to check fresh updates at https://github.com/Lunat1q/Catchem-PoGo or join our friendly Discord chat: https://discord.me/Catchem
[20:48:58] (EGG) Incubator status update: 3.39km left
[20:48:59] (INFO) Travelling to Pokestop: 民間士多 (45m Away)
[20:49:01] (ERROR) Google.Protobuf.InvalidProtocolBufferException: SkipLastField called on an end-group tag, indicating that the corresponding start-group was missing
   at Google.Protobuf.CodedInputStream.SkipLastField()
   at POGOProtos.Networking.Envelopes.ResponseEnvelope.MergeFrom(CodedInputStream input) in D:\catchem\POGOProtos\Networking\Envelopes\ResponseEnvelope.cs:line 283
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProto>d__2`1.MoveNext() in D:\catchem\PoGoAPI\PoGo.RocketAPI\Extensions\HttpClientExtensions.cs:line 119
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__1`2.MoveNext() in D:\catchem\PoGoAPI\PoGo.RocketAPI\Extensions\HttpClientExtensions.cs:line 65
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__7`2.MoveNext() in D:\catchem\PoGoAPI\PoGo.RocketAPI\Rpc\BaseRpc.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Map.<GetIncensePokemons>d__3.MoveNext() in D:\catchem\PoGoAPI\PoGo.RocketAPI\Rpc\Map.cs:line 127
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.PokeMobBot.Logic.Tasks.CatchIncensePokemonsTask.<Execute>d__0.MoveNext() in D:\catchem\PoGo.PokeMobBot.Logic\Tasks\CatchIncensePokemonsTask.cs:line 37
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.PokeMobBot.Logic.Tasks.FarmPokeStopsDiscoveryTask.<>c__DisplayClass2_0.<<MoveToPokestop>b__0>d.MoveNext() in D:\catchem\PoGo.PokeMobBot.Logic\Tasks\FarmPokestopsDiscoveryTask.cs:line 273
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.PokeMobBot.Logic.Navigation.<HumanPathWalking>d__5.MoveNext() in D:\catchem\PoGo.PokeMobBot.Logic\Navigation.cs:line 149
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.PokeMobBot.Logic.HumanNavigation.<Move>d__2.MoveNext() in D:\catchem\PoGo.PokeMobBot.Logic\Navigation2.cs:line 193
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.PokeMobBot.Logic.Tasks.FarmPokeStopsDiscoveryTask.<MoveToPokestop>d__2.MoveNext() in D:\catchem\PoGo.PokeMobBot.Logic\Tasks\FarmPokestopsDiscoveryTask.cs:line 264
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.PokeMobBot.Logic.Tasks.FarmPokeStopsDiscoveryTask.<Execute>d__1.MoveNext() in D:\catchem\PoGo.PokeMobBot.Logic\Tasks\FarmPokestopsDiscoveryTask.cs:line 151
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.PokeMobBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in D:\catchem\PoGo.PokeMobBot.Logic\State\FarmState.cs:line 61
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.PokeMobBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in D:\catchem\PoGo.PokeMobBot.Logic\State\StateMachine.cs:line 39
[20:49:16] (INFO) Logging in using account Google
[20:49:17] (INFO) Playing as *****
[20:49:17] (ATTENTION) Make sure Lat & Lng are right. Exit Program if not! Lat: 22.2937896092591 Lng: 114.16879021165 Alt: 8.49084669360465
[20:49:24] (INFO) During that pause, consider to check fresh updates at https://github.com/Lunat1q/Catchem-PoGo or join our friendly Discord chat: https://discord.me/Catchem
[20:49:25] (EGG) Incubator status update: 3.39km left
[20:49:25] (INFO) Travelling to Pokestop: 民間士多 (33m Away)
[20:49:25] (POKESTOP) Name: 民間士多 XP: 50, Gems: 0, Items: 1 x ItemMaxPotion, 2 x ItemPokeBall
[20:49:27] (PKMN) Throwing Spinning Nice! PokeBall - WILL HIT
[20:49:29] (PKMN) (Success) | Pidgey, Lvl: 9 | CP: (145/479) | IV: 51.11% | Type: Lure | Chance: 50.05% | Dist: 33.31m | Used: PokeBall (260 left) | XP: 120 | Candies: 747

**Comment by CDAGaming** [comment]
A friend of mine had a relativly similar issue to this, but it was fixed by a reinstall of the bot

**Comment by kingkai808** [comment]
the api has changed if you continue to use it you'll get flagged and banned. wait for new api version
