### ISSUE TITLE
keep generate this error

### ISSUE THREAD

**Issue by ijat9917** [Lunat1q/Catchem-PoGo#237]
[04:11:09] (ERROR) System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Enumerator.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at PoGo.PokeMobBot.Logic.MapCache.UsedPokestopsCleanup() in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\MapCache.cs:line 121
   at PoGo.PokeMobBot.Logic.MapCache.CheckPokestopUsed(FortCacheItem fort) in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\MapCache.cs:line 129
   at PoGo.PokeMobBot.Logic.Tasks.FarmPokeStopsDiscoveryTask.<Execute>d__1.MoveNext() in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\Tasks\FarmPokestopsDiscoveryTask.cs:line 114
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.PokeMobBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\State\FarmState.cs:line 58
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.PokeMobBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\State\StateMachine.cs:line 38
[04:11:26] (INFO) Logging in using account Ptc

**Comment by standujar** [comment]
#233 #235 #231

The solution is to use the 1.4.0.0 Rev. :) and wait for the 1.5 or 1.4.5

PLEASE CHECK OTHERS THREADS BEFORE POST
