### ISSUE TITLE
why

### ISSUE THREAD

**Issue by Chris13564** [Lunat1q/Catchem-PoGo#261]
I keep getting this
[19:51:44] (ERROR) System.ArgumentOutOfRangeException: Argument must be in range of -90 to 90
Parameter name: Latitude
   at GeoCoordinatePortable.GeoCoordinate.set_Latitude(Double value) in C:\projects\geocoordinate\src\GeoCoordinatePortable\GeoCoordinate.cs:line 109
   at PoGo.PokeMobBot.Logic.Utils.LocationUtils.CalculateDistanceInMeters(Double sourceLat, Double sourceLng, Double destLat, Double destLng) in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\Utils\LocationUtils.cs:line 16
   at PoGo.PokeMobBot.Logic.MapCache.<>c__DisplayClass6_0.<UpdateMapDatas>b__4(FortData i) in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\MapCache.cs:line 65
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at PoGo.PokeMobBot.Logic.MapCache.<UpdateMapDatas>d__6.MoveNext() in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\MapCache.cs:line 76
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.PokeMobBot.Logic.State.InfoState.<Execute>d__0.MoveNext() in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\State\InfoState.cs:line 21
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.PokeMobBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\State\StateMachine.cs:line 38
[19:52:02] (INFO) Logging in using account Google
[19:52:04] (INFO) Playing as LS1rb262jz
[19:52:04] (ATTENTION) Make sure Lat & Lng are right. Exit Program if not! Lat: 37.793734 Lng: -122.392398
[19:52:05] (ERROR) System.ArgumentOutOfRangeException: Argument must be in range of -90 to 90
Parameter name: Latitude
   at GeoCoordinatePortable.GeoCoordinate.set_Latitude(Double value) in C:\projects\geocoordinate\src\GeoCoordinatePortable\GeoCoordinate.cs:line 109
   at PoGo.PokeMobBot.Logic.Utils.LocationUtils.CalculateDistanceInMeters(Double sourceLat, Double sourceLng, Double destLat, Double destLng) in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\Utils\LocationUtils.cs:line 16
   at PoGo.PokeMobBot.Logic.MapCache.<>c__DisplayClass6_0.<UpdateMapDatas>b__4(FortData i) in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\MapCache.cs:line 65
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at PoGo.PokeMobBot.Logic.MapCache.<UpdateMapDatas>d__6.MoveNext() in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\MapCache.cs:line 76
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.PokeMobBot.Logic.State.InfoState.<Execute>d__0.MoveNext() in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\State\InfoState.cs:line 21
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.PokeMobBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\State\StateMachine.cs:line 38
[19:52:18] (INFO) Logging in using account Google
[19:52:20] (INFO) Playing as LS1rb262jz
[19:52:20] (ATTENTION) Make sure Lat & Lng are right. Exit Program if not! Lat: 37.793734 Lng: -122.392398
[19:52:21] (ERROR) System.ArgumentOutOfRangeException: Argument must be in range of -90 to 90
Parameter name: Latitude
   at GeoCoordinatePortable.GeoCoordinate.set_Latitude(Double value) in C:\projects\geocoordinate\src\GeoCoordinatePortable\GeoCoordinate.cs:line 109
   at PoGo.PokeMobBot.Logic.Utils.LocationUtils.CalculateDistanceInMeters(Double sourceLat, Double sourceLng, Double destLat, Double destLng) in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\Utils\LocationUtils.cs:line 16
   at PoGo.PokeMobBot.Logic.MapCache.<>c__DisplayClass6_0.<UpdateMapDatas>b__4(FortData i) in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\MapCache.cs:line 65
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at PoGo.PokeMobBot.Logic.MapCache.<UpdateMapDatas>d__6.MoveNext() in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\MapCache.cs:line 76
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.PokeMobBot.Logic.State.InfoState.<Execute>d__0.MoveNext() in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\State\InfoState.cs:line 21
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.PokeMobBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\State\StateMachine.cs:line 38
[19:52:36] (INFO) Logging in using account Google
[19:52:37] (INFO) Playing as LS1rb262jz
[19:52:37] (ATTENTION) Make sure Lat & Lng are right. Exit Program if not! Lat: 37.793734 Lng: -122.392398
[19:52:39] (ERROR) System.ArgumentOutOfRangeException: Argument must be in range of -90 to 90
Parameter name: Latitude
   at GeoCoordinatePortable.GeoCoordinate.set_Latitude(Double value) in C:\projects\geocoordinate\src\GeoCoordinatePortable\GeoCoordinate.cs:line 109
   at PoGo.PokeMobBot.Logic.Utils.LocationUtils.CalculateDistanceInMeters(Double sourceLat, Double sourceLng, Double destLat, Double destLng) in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\Utils\LocationUtils.cs:line 16
   at PoGo.PokeMobBot.Logic.MapCache.<>c__DisplayClass6_0.<UpdateMapDatas>b__4(FortData i) in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\MapCache.cs:line 65
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at PoGo.PokeMobBot.Logic.MapCache.<UpdateMapDatas>d__6.MoveNext() in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\MapCache.cs:line 76
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.PokeMobBot.Logic.State.InfoState.<Execute>d__0.MoveNext() in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\State\InfoState.cs:line 21
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.PokeMobBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\State\StateMachine.cs:line 38
[19:52:57] (INFO) Logging in using account Google
[19:52:58] (INFO) Playing as LS1rb262jz
[19:52:58] (ATTENTION) Make sure Lat & Lng are right. Exit Program if not! Lat: 37.793734 Lng: -122.392398
[19:53:00] (ERROR) System.ArgumentOutOfRangeException: Argument must be in range of -90 to 90
Parameter name: Latitude
   at GeoCoordinatePortable.GeoCoordinate.set_Latitude(Double value) in C:\projects\geocoordinate\src\GeoCoordinatePortable\GeoCoordinate.cs:line 109
   at PoGo.PokeMobBot.Logic.Utils.LocationUtils.CalculateDistanceInMeters(Double sourceLat, Double sourceLng, Double destLat, Double destLng) in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\Utils\LocationUtils.cs:line 16
   at PoGo.PokeMobBot.Logic.MapCache.<>c__DisplayClass6_0.<UpdateMapDatas>b__4(FortData i) in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\MapCache.cs:line 65
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at PoGo.PokeMobBot.Logic.MapCache.<UpdateMapDatas>d__6.MoveNext() in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\MapCache.cs:line 76
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.PokeMobBot.Logic.State.InfoState.<Execute>d__0.MoveNext() in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\State\InfoState.cs:line 21
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.PokeMobBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\State\StateMachine.cs:line 38
[19:53:15] (INFO) Logging in using account Google
[19:53:16] (INFO) Playing as LS1rb262jz
[19:53:16] (ATTENTION) Make sure Lat & Lng are right. Exit Program if not! Lat: 37.793734 Lng: -122.392398
[19:53:18] (ERROR) System.ArgumentOutOfRangeException: Argument must be in range of -90 to 90
Parameter name: Latitude
   at GeoCoordinatePortable.GeoCoordinate.set_Latitude(Double value) in C:\projects\geocoordinate\src\GeoCoordinatePortable\GeoCoordinate.cs:line 109
   at PoGo.PokeMobBot.Logic.Utils.LocationUtils.CalculateDistanceInMeters(Double sourceLat, Double sourceLng, Double destLat, Double destLng) in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\Utils\LocationUtils.cs:line 16
   at PoGo.PokeMobBot.Logic.MapCache.<>c__DisplayClass6_0.<UpdateMapDatas>b__4(FortData i) in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\MapCache.cs:line 65
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at PoGo.PokeMobBot.Logic.MapCache.<UpdateMapDatas>d__6.MoveNext() in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\MapCache.cs:line 76
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.PokeMobBot.Logic.State.InfoState.<Execute>d__0.MoveNext() in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\State\InfoState.cs:line 21
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.PokeMobBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\State\StateMachine.cs:line 38
[19:53:34] (INFO) Logging in using account Google
[19:53:36] (INFO) Playing as LS1rb262jz
[19:53:36] (ATTENTION) Make sure Lat & Lng are right. Exit Program if not! Lat: 37.793734 Lng: -122.392398
[19:53:38] (ERROR) System.ArgumentOutOfRangeException: Argument must be in range of -90 to 90
Parameter name: Latitude
   at GeoCoordinatePortable.GeoCoordinate.set_Latitude(Double value) in C:\projects\geocoordinate\src\GeoCoordinatePortable\GeoCoordinate.cs:line 109
   at PoGo.PokeMobBot.Logic.Utils.LocationUtils.CalculateDistanceInMeters(Double sourceLat, Double sourceLng, Double destLat, Double destLng) in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\Utils\LocationUtils.cs:line 16
   at PoGo.PokeMobBot.Logic.MapCache.<>c__DisplayClass6_0.<UpdateMapDatas>b__4(FortData i) in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\MapCache.cs:line 65
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at PoGo.PokeMobBot.Logic.MapCache.<UpdateMapDatas>d__6.MoveNext() in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\MapCache.cs:line 76
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.PokeMobBot.Logic.State.InfoState.<Execute>d__0.MoveNext() in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\State\InfoState.cs:line 21
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.PokeMobBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\State\StateMachine.cs:line 38

**Comment by Scoopedd** [comment]
looks like you banned... if you sent your settings i can perhaps help you why ;) got 3 accounts right now and no one is banned its very important to set a "real" phone and slow the bot manualy down!

**Comment by xTeddiusx** [comment]
I think that -122.392398 is the problem !!

Make sure Lat & Lng are right. Exit Program if not! Lat: 37.793734 Lng: -122.392398
19:53:38 System.ArgumentOutOfRangeException: Argument must be in range of -90 to 90
