### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by VinceHJW** [Lunat1q/Catchem-PoGo#268]
I keep having this error code : 
"[21:49:30] (ERROR) System.NullReferenceException: Object reference not set to an instance of an object.
   at PoGo.PokeMobBot.Logic.Tasks.SnipePokemonTask.<>c__DisplayClass10_0.<Start>b__0(SniperInfo x) in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\Tasks\SnipePokemonTask.cs:line 613
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at PoGo.PokeMobBot.Logic.Tasks.SnipePokemonTask.<Start>d__10.MoveNext() in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\Tasks\SnipePokemonTask.cs:line 612"
Any help?

**Comment by standujar** [comment]
using snip ?

**Comment by VinceHJW** [comment]
yes..

**Comment by Bay101** [comment]
Sniping is currently not implemented, Please read the Wiki before posting issues.
