### ISSUE TITLE
Error and then restart?!

### ISSUE THREAD

**Issue by raul4152** [Lunat1q/Catchem-PoGo#287]
[17:29:59] (ERROR) System.NullReferenceException: Object reference not set to an instance of an object.
   at PoGo.PokeMobBot.Logic.Tasks.CatchLurePokemonsTask.<Execute>d__0.MoveNext() in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\Tasks\CatchLurePokemonsTask.cs:line 33
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.PokeMobBot.Logic.Tasks.UseNearbyPokestopsTask.<Execute>d__0.MoveNext() in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\Tasks\UseNearbyPokestopsTask.cs:line 70
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.PokeMobBot.Logic.Tasks.ForceMoveTask.<>c__DisplayClass1_0.<<Execute>b__1>d.MoveNext() in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\Tasks\ForceMoveTask.cs:line 53
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.PokeMobBot.Logic.Navigation.<HumanPathWalking>d__5.MoveNext() in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\Navigation.cs:line 224
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.PokeMobBot.Logic.HumanNavigation.<Move>d__3.MoveNext() in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\Navigation2.cs:line 186
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.PokeMobBot.Logic.Tasks.ForceMoveTask.<Execute>d__1.MoveNext() in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\Tasks\ForceMoveTask.cs:line 41
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.PokeMobBot.Logic.HumanNavigation.<Move>d__3.MoveNext() in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\Navigation2.cs:line 175
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.PokeMobBot.Logic.Tasks.ForceMoveTask.<Execute>d__1.MoveNext() in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\Tasks\ForceMoveTask.cs:line 41
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.PokeMobBot.Logic.HumanNavigation.<Move>d__3.MoveNext() in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\Navigation2.cs:line 175
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.PokeMobBot.Logic.Tasks.FarmPokeStopsDiscoveryTask.<MoveToPokestop>d__2.MoveNext() in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\Tasks\FarmPokestopsDiscoveryTask.cs:line 201
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.PokeMobBot.Logic.Tasks.FarmPokeStopsDiscoveryTask.<Execute>d__1.MoveNext() in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\Tasks\FarmPokestopsDiscoveryTask.cs:line 120
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.PokeMobBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\State\FarmState.cs:line 58
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.PokeMobBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\State\StateMachine.cs:line 38

**Comment by ojooscuro** [comment]
Having the same problema? Someone knows how to fix it?

**Comment by Lunat1q** [comment]
I'll fix it

**Comment by Lunat1q** [comment]
Are u sure you are using latest release?
