### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by wagas** [Lunat1q/Catchem-PoGo#395]
16:23:57] (INFO) Logging in using account Google
[16:23:59] (ERROR) As you have Google Two Factor Auth enabled, you will need to insert an App Specific Password into the auth.json
[16:23:59] (ERROR) Opening Google App-Passwords. Please make a new App Password (use Other as Device)
[16:24:00] (ERROR) Current Operation was canceled.

i tried to put proxy

**Comment by wagas** [comment]
[16:30:00] (ERROR) Google.Protobuf.InvalidProtocolBufferException: SkipLastField called on an end-group tag, indicating that the corresponding start-group was missing
   at Google.Protobuf.CodedInputStream.SkipLastField()
   at POGOProtos.Networking.Envelopes.ResponseEnvelope.MergeFrom(CodedInputStream input) in D:\Ketchum\Catchem-PoGo\POGOProtos\Networking\Envelopes\ResponseEnvelope.cs:line 283
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProto>d__2`1.MoveNext() in D:\Ketchum\Catchem-PoGo\PokemonGoAPI\PokemonGo.RocketAPI\Extensions\HttpClientExtensions.cs:line 105
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__1`2.MoveNext() in D:\Ketchum\Catchem-PoGo\PokemonGoAPI\PokemonGo.RocketAPI\Extensions\HttpClientExtensions.cs:line 65
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__6`2.MoveNext() in D:\Ketchum\Catchem-PoGo\PokemonGoAPI\PokemonGo.RocketAPI\Rpc\BaseRpc.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Player.<GetPlayer>d__4.MoveNext() in D:\Ketchum\Catchem-PoGo\PokemonGoAPI\PokemonGo.RocketAPI\Rpc\Player.cs:line 53
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.PokeMobBot.Logic.State.LoginState.<DownloadProfile>d__2.MoveNext() in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\State\LoginState.cs:line 225
[16:30:00] (ERROR) Current Operation was canceled.

**Comment by Lunat1q** [comment]
try to read console, and DO what it says.

**Comment by wagas** [comment]
i already done it.. still the same
