### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by wagas** [Lunat1q/Catchem-PoGo#403]
[21:04:25] (INFO) Logging in using account Google
[21:05:07] (ERROR) PokemonGo.RocketAPI.Exceptions.GoogleOfflineException: Exception of type 'PokemonGo.RocketAPI.Exceptions.GoogleOfflineException' was thrown.
   at PokemonGo.RocketAPI.Login.GoogleLogin.<GetAccessToken>d__4.MoveNext() in D:\Ketchum\Catchem-PoGo\PokemonGoAPI\PokemonGo.RocketAPI\Login\GoogleLogin.cs:line 32
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__3.MoveNext() in D:\Ketchum\Catchem-PoGo\PokemonGoAPI\PokemonGo.RocketAPI\Rpc\Login.cs:line 53
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.PokeMobBot.Logic.State.LoginState.<Execute>d__0.MoveNext() in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\State\LoginState.cs:line 32
[21:05:07] (INFO) Trying again in 45 seconds...
[21:05:12] (ERROR) Current Operation was canceled.

**Comment by kollp3** [comment]
not 100% sure but it looks like the perm. ban.

**Comment by ranrinc** [comment]
Perm. Ban.. sorry guy..

**Comment by Lunat1q** [comment]
You have problems with connection to google, it's not perma ban.
