### ISSUE TITLE
What this , help me pls ?

### ISSUE THREAD

**Issue by OSIRISzzGOD** [Lunat1q/Catchem-PoGo#497]
11:16:40] (ERROR) System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at Google.Protobuf.ProtoPreconditions.CheckNotNull[T](T value, String name)
   at POGOProtos.Networking.Requests.Messages.ClaimCodenameMessage.set_Codename(String value) in D:\Ketchum\Catchem-PoGo\POGOProtos\Networking\Requests\Messages\ClaimCodenameMessage.cs:line 78
   at PokemonGo.RocketAPI.Rpc.Misc.<ClaimCodename>d__1.MoveNext() in D:\Ketchum\Catchem-PoGo\PokemonGoAPI\PokemonGo.RocketAPI\Rpc\Misc.cs:line 19
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.PokeMobBot.Logic.State.CheckTosState.<SelectNicnname>d__2.MoveNext() in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\State\CheckTosState.cs:line 118
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.PokeMobBot.Logic.State.CheckTosState.<Execute>d__0.MoveNext() in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\State\CheckTosState.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.PokeMobBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\State\StateMachine.cs:line 38

**Comment by Lunat1q** [comment]
U forgot to pick the name. Will fix it

**Comment by Lunat1q** [comment]
fixed. in next release.

**Comment by OSIRISzzGOD** [comment]
Now i fill name in the D# _**esire Nick**_ 
Bot just running None Problem ,Thx a lot
