### ISSUE TITLE
getting an error

### ISSUE THREAD

**Issue by chyle** [Lunat1q/Catchem-PoGo#56]
Hi.. its been working fine until this showed up..

[04:43:46] (ERROR) System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at PoGo.PokeMobBot.Logic.Tasks.FarmPokeStopsDiscoveryTask.<Execute>d__1.MoveNext() in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\Tasks\FarmPokestopsDiscoveryTask.cs:line 60
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.PokeMobBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\State\FarmState.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.PokeMobBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\State\StateMachine.cs:line 38

![image](https://cloud.githubusercontent.com/assets/21027036/17651937/91db26ce-62a3-11e6-90e8-b9c6d5d17a99.png)

thanks!

**Comment by chyle** [comment]
And can someone tell me what is the meaning of the number located at the upper right of the picture
![image](https://cloud.githubusercontent.com/assets/21027036/17651961/f54234a0-62a3-11e6-8a30-f0fb1cf01493.png)

**Comment by chyle** [comment]
My God! this is by far the Safest and the best bot ive used!!!!!! Thanks you for creating this wonderful bot! my routine is : bot it for 4-5hrs.. change IP.. use a diff account.. bot again for 4-5hrs.. no softban or anything.. just dont be greedy peepzz...  thanks @Lunat1q !!!

**Comment by chyle** [comment]
after updating the bot to 
![image](https://cloud.githubusercontent.com/assets/21027036/17652220/6a0a2e14-62a9-11e6-8c59-ce73e4e7b19c.png)

still getting the same error message...

![image](https://cloud.githubusercontent.com/assets/21027036/17652216/4b46ca8c-62a9-11e6-9ecf-3e7014c1588a.png)

![image](https://cloud.githubusercontent.com/assets/21027036/17652217/55046098-62a9-11e6-91db-580c7a595d41.png)

**Comment by skzbr** [comment]
Yep, its happening for me too.

**Comment by Lunat1q** [comment]
I'll take a look

**Comment by keroberus** [comment]
same error here 
+ re[ lunat this is so far the best bot

**Comment by Lunat1q** [comment]
Fixed. Will be published next release.
