### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by timmy83yee** [Lunat1q/Catchem-PoGo#567]
[16:54:19] (ERROR) System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at PoGo.PokeMobBot.Logic.Utils.MapMatrix..ctor(IEnumerable`1 forts, FortCacheItem fortToStart, Int32 fortsToVisit, Boolean nearestNeigh) in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\Utils\RoutingUtils.cs:line 39
   at PoGo.PokeMobBot.Logic.Utils.RoutingUtils.GetBestRoute(FortCacheItem startingPokestop, IEnumerable`1 pokestopsList, Int32 amountToVisit) in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\Utils\RoutingUtils.cs:line 15
   at PoGo.PokeMobBot.Logic.Tasks.FarmPokestopsTask.<NoTeleport>d__3.MoveNext() in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\Tasks\FarmPokestopsTask.cs:line 366
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.PokeMobBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__1.MoveNext() in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\Tasks\FarmPokestopsTask.cs:line 34
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.PokeMobBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\State\FarmState.cs:line 60
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.PokeMobBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\State\StateMachine.cs:line 38

---------------------------------------------------------------------------------------------------------------
what does this error means?
it never happen before since i used this BOT

**Comment by Lunat1q** [comment]
i'll take a look, wait for a next release.
