### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by louloufafa** [Lunat1q/Catchem-PoGo#657]
[14:34:24] (ERROR) System.MissingMethodException: Method not found: 'Void System.Diagnostics.Tracing.FrameworkEventSource.BeginGetResponse(System.Object, System.String)'.
   at System.Net.HttpWebRequest.BeginGetResponse(AsyncCallback callback, Object state)
   at System.Net.Http.HttpClientHandler.StartGettingResponse(RequestState state)
   at System.Net.Http.HttpClientHandler.StartRequest(Object obj)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Login.PtcLogin.<GetSessionCookie>d__9.MoveNext() in C:\Users\m.podolskiy\Desktop\Ketchum_dev\Catchem-PoGo\PoGoAPI\PoGo.RocketAPI\Login\PtcLogin.cs:line 94
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Login.PtcLogin.<GetAccessToken>d__4.MoveNext() in C:\Users\m.podolskiy\Desktop\Ketchum_dev\Catchem-PoGo\PoGoAPI\PoGo.RocketAPI\Login\PtcLogin.cs:line 35
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__3.MoveNext() in C:\Users\m.podolskiy\Desktop\Ketchum_dev\Catchem-PoGo\PoGoAPI\PoGo.RocketAPI\Rpc\Login.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.PokeMobBot.Logic.State.LoginState.<Execute>d__0.MoveNext() in C:\Users\m.podolskiy\Desktop\Ketchum_dev\Catchem-PoGo\PoGo.PokeMobBot.Logic\State\LoginState.cs:line 32

**Comment by hazmad** [comment]
try logging in with the app

**Comment by Lunat1q** [comment]
Try to update .net or dl latest release
