### ISSUE TITLE
Is this error because of my config? any one see this?

### ISSUE THREAD

**Issue by gundamdnt** [Lunat1q/Catchem-PoGo#665]
[11:32:39] (ERROR) System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at PoGo.PokeMobBot.Logic.Utils.MapMatrix..ctor(IEnumerable`1 forts, FortCacheItem fortToStart, Int32 fortsToVisit, Boolean nearestNeigh) in C:\Users\m.podolskiy\Desktop\Ketchum_dev\Catchem-PoGo\PoGo.PokeMobBot.Logic\Utils\RoutingUtils.cs:line 38
   at PoGo.PokeMobBot.Logic.Utils.RoutingUtils.GetBestRoute(FortCacheItem startingPokestop, IEnumerable`1 pokestopsList, Int32 amountToVisit) in C:\Users\m.podolskiy\Desktop\Ketchum_dev\Catchem-PoGo\PoGo.PokeMobBot.Logic\Utils\RoutingUtils.cs:line 14
   at PoGo.PokeMobBot.Logic.Tasks.FarmPokestopsTask.<NoTeleport>d__3.MoveNext() in C:\Users\m.podolskiy\Desktop\Ketchum_dev\Catchem-PoGo\PoGo.PokeMobBot.Logic\Tasks\FarmPokestopsTask.cs:line 332
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.PokeMobBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__1.MoveNext() in C:\Users\m.podolskiy\Desktop\Ketchum_dev\Catchem-PoGo\PoGo.PokeMobBot.Logic\Tasks\FarmPokestopsTask.cs:line 34
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.PokeMobBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in C:\Users\m.podolskiy\Desktop\Ketchum_dev\Catchem-PoGo\PoGo.PokeMobBot.Logic\State\FarmState.cs:line 61
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.PokeMobBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\Users\m.podolskiy\Desktop\Ketchum_dev\Catchem-PoGo\PoGo.PokeMobBot.Logic\State\StateMachine.cs:line 38

**Comment by Bay101** [comment]
What routing provider are you using?

**Comment by gundamdnt** [comment]
Google direction API

**Comment by mfkk3** [comment]
i got same problem

**Comment by Lunat1q** [comment]
Download latest release.
