### ISSUE TITLE
It auto crasches everytime i start it

### ISSUE THREAD

**Issue by BrLord** [Lunat1q/Catchem-PoGo#86]
It is actually crashing after 30 seconds, sometimes i doesn't even start. also i can't create a new bot without it crashing too. It is crashing A LOT. Thanks in advance for all your time spent on this project ;D

**Comment by skzbr** [comment]
Yep, it`s crashing sometimes

**Comment by Lunat1q** [comment]
try to put logs here.

**Comment by CaMoTraX** [comment]
Same Here

**Comment by skzbr** [comment]
Just it:

Initializing Rocket logger at time 15/08/2016 15:46:25...

When starts, just crash.

**Comment by skzbr** [comment]
This, after get banned by spawning on 0,0,0

Initializing Rocket logger at time 15/08/2016 16:02:06...
[16:03:04] AutoUpdater is disabled. Get the latest release from: https://github.com/Lunat1q/Catchem-PoGo/releases
 
Initializing Rocket logger at time 15/08/2016 16:03:16...
[16:03:28] AutoUpdater is disabled. Get the latest release from: https://github.com/Lunat1q/Catchem-PoGo/releases
 
[16:03:28] Logging in using account Google
[16:03:30] Playing as ------
[16:03:30] Current Operation was canceled.
[16:03:40] AutoUpdater is disabled. Get the latest release from: https://github.com/Lunat1q/Catchem-PoGo/releases
 
[16:03:40] Logging in using account Google
[16:03:41] Playing as ------
[16:03:41] Make sure Lat & Lng are right. Exit Program if not! Lat: -23,5845327584374 Lng: -46,6596659640407
[16:03:41] System.ArgumentNullException: Valor não pode ser nulo.
Nome do parâmetro: source
   em System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   em PoGo.PokeMobBot.Logic.Inventory.<GetHighestsCp>d__18.MoveNext() na D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\Inventory.cs:linha 229
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em PoGo.PokeMobBot.Logic.Tasks.DisplayPokemonStatsTask.<Execute>d__2.MoveNext() na D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\Tasks\DisplayPokemonStatsTask.cs:linha 28
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em PoGo.PokeMobBot.Logic.State.InfoState.<Execute>d__0.MoveNext() na D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\State\InfoState.cs:linha 20
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em PoGo.PokeMobBot.Logic.State.StateMachine.<Start>d__3.MoveNext() na D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\State\StateMachine.cs:linha 38
[16:03:58] Current Operation was canceled.
[16:04:33] AutoUpdater is disabled. Get the latest release from: https://github.com/Lunat1q/Catchem-PoGo/releases
 
[16:04:33] Logging in using account Google
[16:04:34] Playing as -------
Initializing Rocket logger at time 15/08/2016 16:06:01...
[16:06:25] AutoUpdater is disabled. Get the latest release from: https://github.com/Lunat1q/Catchem-PoGo/releases
 
[16:06:25] Logging in using account Google
[16:06:27] Playing as GuiOzores


**I think this means when cannot connect to the server, failed to login (ban)**

**Comment by BrLord** [comment]
It is auto-closing, no logs o.O

**Comment by Lunat1q** [comment]
there is Logs folder under profile.

**Comment by munchieiam** [comment]
I got the same thing:

Initializing Rocket logger at time 8/15/2016 4:51:22 PM...
[16:52:05] AutoUpdater is disabled. Get the latest release from: https://github.com/Lunat1q/Catchem-PoGo/releases
 
[16:52:06] Logging in using account Ptc
[16:52:08] Playing as trilmania
[16:52:09] Make sure Lat & Lng are right. Exit Program if not! Lat: 32.7693620000003 Lng: -79.9297540000005
[16:52:09] System.NullReferenceException: Object reference not set to an instance of an object.
   at PoGo.PokeMobBot.Logic.Inventory.<GetPokemons>d__29.MoveNext() in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\Inventory.cs:line 426
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.PokeMobBot.Logic.Inventory.<GetHighestsCp>d__18.MoveNext() in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\Inventory.cs:line 229
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.PokeMobBot.Logic.Tasks.DisplayPokemonStatsTask.<Execute>d__2.MoveNext() in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\Tasks\DisplayPokemonStatsTask.cs:line 28
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.PokeMobBot.Logic.State.InfoState.<Execute>d__0.MoveNext() in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\State\InfoState.cs:line 20
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.PokeMobBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\State\StateMachine.cs:line 38
[16:52:27] Logging in using account Ptc
[16:52:29] Playing as trilmania
[16:52:29] Make sure Lat & Lng are right. Exit Program if not! Lat: 32.7693620000003 Lng: -79.9297540000005
[16:52:29] System.NullReferenceException: Object reference not set to an instance of an object.
   at PoGo.PokeMobBot.Logic.Inventory.<GetPokemons>d__29.MoveNext() in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\Inventory.cs:line 426
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.PokeMobBot.Logic.Inventory.<GetHighestsCp>d__18.MoveNext() in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\Inventory.cs:line 229
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.PokeMobBot.Logic.Tasks.DisplayPokemonStatsTask.<Execute>d__2.MoveNext() in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\Tasks\DisplayPokemonStatsTask.cs:line 28
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.PokeMobBot.Logic.State.InfoState.<Execute>d__0.MoveNext() in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\State\InfoState.cs:line 20
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.PokeMobBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\State\StateMachine.cs:line 38
[16:52:44] Current Operation was canceled.

**Comment by kvarnis33** [comment]
**Same problem here...**

[22:53:54] AutoUpdater is disabled. Get the latest release from: https://github.com/Lunat1q/Catchem-PoGo/releases
 
[22:53:54] Logging in using account Ptc
[22:53:56] Playing as *******


**_Then the program crashes..._**

**Comment by BrLord** [comment]
My loh is exactly like that ^^^^^^

**Comment by PassiveModding** [comment]
mine crashes, however itll run for a few minutes before then just stop working altogether.
nothing shows in the logs other than what has been running previously

**Comment by fexnax** [comment]
Hi could you help me with the next problem, when i tried to start appear the following error:

[16:50:48] (ERROR) Current Operation was canceled.
[16:50:58] (UPDATE) Perfect! You already have the newest Version 1.3.2.1
[16:50:58] (INFO) Logging in using account Google
[16:50:59] (INFO) Playing as ----
[16:50:59] (ATTENTION) Make sure Lat & Lng are right. Exit Program if not! Lat: -- Lng: --
[16:50:59] (ERROR) System.ArgumentNullException: El valor no puede ser nulo.
Nombre del parámetro: source
   en System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   en PoGo.PokeMobBot.Logic.Inventory.<GetHighestsCp>d__18.MoveNext() en D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\Inventory.cs:línea 229
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en PoGo.PokeMobBot.Logic.Tasks.DisplayPokemonStatsTask.<Execute>d__2.MoveNext() en D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\Tasks\DisplayPokemonStatsTask.cs:línea 28
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en PoGo.PokeMobBot.Logic.State.InfoState.<Execute>d__0.MoveNext() en D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\State\InfoState.cs:línea 20
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en PoGo.PokeMobBot.Logic.State.StateMachine.<Start>d__3.MoveNext() en D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\State\StateMachine.cs:línea 38

**Comment by DVD-DY** [comment]
Same problem

[18:23:09] Perfect! You already have the newest Version 1.3.2.1
[18:23:09] Logging in using account Ptc
[18:23:30] Logging in using account Ptc
[18:23:39] Playing as ******
Initializing Rocket logger at time 15/08/2016 06:24:01...
[18:25:20] Perfect! You already have the newest Version 1.3.2.1
[18:25:20] Logging in using account Ptc
[18:25:26] Playing as ******
Initializing Rocket logger at time 15/08/2016 06:25:42...
[18:26:49] Perfect! You already have the newest Version 1.3.2.1
[18:26:49] Logging in using account Ptc
[18:26:57] Playing as ******
[18:26:58] Current Operation was canceled.
Initializing Rocket logger at time 15/08/2016 06:27:04...
[18:28:12] Perfect! You already have the newest Version 1.3.2.1
[18:28:12] Logging in using account Ptc
[18:28:20] Playing as ******
Initializing Rocket logger at time 15/08/2016 06:28:30...
[18:29:50] Perfect! You already have the newest Version 1.3.2.1
[18:29:50] Logging in using account Ptc
[18:29:57] Playing as ******
Initializing Rocket logger at time 15/08/2016 06:30:08...
[18:31:27] Perfect! You already have the newest Version 1.3.2.1
[18:31:27] Logging in using account Ptc
[18:31:35] Playing as ******
Initializing Rocket logger at time 15/08/2016 06:31:49...
[18:32:21] Perfect! You already have the newest Version 1.3.2.1
[18:32:21] Logging in using account Ptc
[18:32:28] Playing as ******
Initializing Rocket logger at time 15/08/2016 06:43:44...
[18:44:06] Perfect! You already have the newest Version 1.3.2.1
[18:44:06] Logging in using account Ptc
[18:44:14] Playing as ******

**Comment by poetawd** [comment]
Hello !

I am also having this problem.... I think it is related to coordinates. I had a similar issue with another BOT.

In some languages the coordinates are separeted by comma ( , ) and others by a point ( . ). In my case, it is separeted by a comma, My window is set up in PORTUGUESE-BRAZIL.

I see in the logs sent by other users that most are using SPANISH or PORTUGUESE OS.

When I use coordinates separted by points, it will make my BOT to crash, when I use it separeted by comma, it will remove the comma and put me somewhere weird.

The version 1.2.5 was working perfectly for me !

Thank you !

**Comment by progdawn** [comment]
I am also having this issue. Attached is my config file, the log file, and then a copy-paste file of the exact error. 
[config.txt](https://github.com/Lunat1q/Catchem-PoGo/files/419226/config.txt)
[copypaste.txt](https://github.com/Lunat1q/Catchem-PoGo/files/419227/copypaste.txt)
[PokeMobBot-2016-08-15-19.txt](https://github.com/Lunat1q/Catchem-PoGo/files/419228/PokeMobBot-2016-08-15-19.txt)

**Comment by ShadyBS** [comment]
its the coordinates like @poetawd said. The bot is messing them up

**Comment by Lunat1q** [comment]
fixed
