### ISSUE TITLE
Bug, Stopped bot

### ISSUE THREAD

**Issue by Slipknotivo2** [Lunat1q/Catchem-PoGo#914]
00:37:55] (ERROR) System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at Google.Protobuf.ProtoPreconditions.CheckNotNull[T](T value, String name)
   at POGOProtos.Networking.Envelopes.RequestEnvelope.Types.AuthInfo.Types.JWT.set_Contents(String value) in D:\Catchem-PoGo\POGOProtos\Networking\Envelopes\RequestEnvelope.cs:line 588
   at PokemonGo.RocketAPI.Helpers.RequestBuilder.GetInitialRequestEnvelope(Request[] customRequests) in D:\Catchem-PoGo\PoGoAPI\PoGo.RocketAPI\Helpers\RequestBuilder.cs:line 289
   at PokemonGo.RocketAPI.Rpc.Login.<SetServer>d__4.MoveNext() in D:\Catchem-PoGo\PoGoAPI\PoGo.RocketAPI\Rpc\Login.cs:line 76
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__3.MoveNext() in D:\Catchem-PoGo\PoGoAPI\PoGo.RocketAPI\Rpc\Login.cs:line 55
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.PokeMobBot.Logic.State.LoginState.<Execute>d__0.MoveNext() in D:\Catchem-PoGo\PoGo.PokeMobBot.Logic\State\LoginState.cs:line 32
[00:38:45] (ATTENTION) Current Operation was canceled. Bot stopped/paused.

**Comment by Slipknotivo2** [comment]
[00:40:22] (ERROR) APIFailureStrategy (Exception): A task was canceled.
[00:40:44] (ERROR) APIFailureStrategy (Exception): Exception of type 'PokemonGo.RocketAPI.Exceptions.PtcOfflineException' was thrown.

Bot run 15/20 minutes and error.

**Comment by Cryptologism** [comment]
You are using google auth right?
Or maybe you are using Google api key?

**Comment by Cryptologism** [comment]
For me never meet this error before... Im usong mapzen api last night so far no problem at all... Well try to recheck all setting,internet connection,graphic like netframework, and etc

**Comment by Slipknotivo2** [comment]
No, use PTC and no have api key, use default map

**Comment by Slipknotivo2** [comment]
i have 2 pcs and bug in 2 pc (S.O Win Server 2008) sorry bad english, i speack spanish :P

**Comment by Cryptologism** [comment]
Hmmmuse latest version? 
Or try to download fresh new copy no change anything,insert credential then try to start again

**Comment by Cryptologism** [comment]
Win server 2008... Ermmmm are those os support for this... As far as i know mybe it lilte complicated using server os since they have different file build in... Try use vmware or vbox window 7 or 8 in 32 or 64 bit...

**Comment by Slipknotivo2** [comment]
Yes, i have 1.4.9.0, only changed Name Account, Pass, Latitude, Longitude and Device Info

**Comment by Slipknotivo2** [comment]
Have VPS's and only work Win server 2003/2008 or Linux

**Comment by Cryptologism** [comment]
So u using vps which is only support these server os and linux... Ermmm i think i saw somewhere that for linux were not develop yet for CatchEm.. Not sure about window server.. Need an answer from Sir Lunatics himself... 
Other wise try to install vbox or vmware and botting into it without vps for moment to see if problem still exist..

**Comment by Slipknotivo2** [comment]
i use Tor Browser and Proxifier for proxy sistem, ip 127.0.0.1:9150 no work in catchem. In win 10 64 Bits pro have same problem

**Comment by Cryptologism** [comment]
Wow sound complicated... Os server + tor brwser and proxifier to more proxy... With ip offline.. 127.0.0.1 port 9150..  
With os win 10 64 bit also same problem? Aw... Looks like something bug mybe... Try to ask Sir Lunatics soon or others devs

**Comment by Slipknotivo2** [comment]
Change Proxifier for Proxycap and for moment 100% work proxy sistem red tor

**Comment by Bay101** [comment]
If you are using mobot routing API it is now a paid service and you need an API key :smiley:

**Comment by Slipknotivo2** [comment]
this bug of catchem, plz verify source code. thanks
