### ISSUE TITLE
Bug crash catchem

### ISSUE THREAD

**Issue by Slipknotivo2** [Lunat1q/Catchem-PoGo#929]
[02:39:01] (ERROR) Google.Protobuf.InvalidProtocolBufferException: SkipLastField called on an end-group tag, indicating that the corresponding start-group was missing
   at Google.Protobuf.CodedInputStream.SkipLastField()
   at POGOProtos.Networking.Envelopes.ResponseEnvelope.MergeFrom(CodedInputStream input) in D:\Catchem-PoGo\POGOProtos\Networking\Envelopes\ResponseEnvelope.cs:line 283
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProto>d__2`1.MoveNext() in D:\Catchem-PoGo\PoGoAPI\PoGo.RocketAPI\Extensions\HttpClientExtensions.cs:line 119
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__1`2.MoveNext() in D:\Catchem-PoGo\PoGoAPI\PoGo.RocketAPI\Extensions\HttpClientExtensions.cs:line 65
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__7`2.MoveNext() in D:\Catchem-PoGo\PoGoAPI\PoGo.RocketAPI\Rpc\BaseRpc.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Player.<GetPlayer>d__4.MoveNext() in D:\Catchem-PoGo\PoGoAPI\PoGo.RocketAPI\Rpc\Player.cs:line 53
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.PokeMobBot.Logic.State.LoginState.<DownloadProfile>d__2.MoveNext() in D:\Catchem-PoGo\PoGo.PokeMobBot.Logic\State\LoginState.cs:line 225

All Routing service same error, this bug is other

**Comment by animekk** [comment]
Find an answer:
https://discord.gg/6z5AMX5
