### ISSUE TITLE
unknown issue 

### ISSUE THREAD

**Issue by soramachi** [Lunat1q/Catchem-PoGo#944]
[14:07:39] (ERROR) System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at PoGo.PokeMobBot.Logic.API.MapzenAPI.CheckForExistingAltitude(Double lat, Double lon) in D:\Catchem-PoGo\PoGo.PokeMobBot.Logic\API\MapzenAPI.cs:line 214
   at PoGo.PokeMobBot.Logic.API.MapzenAPI.<FillAltitude>d__21.MoveNext() in D:\Catchem-PoGo\PoGo.PokeMobBot.Logic\API\MapzenAPI.cs:line 261
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.PokeMobBot.Logic.HumanNavigation.<Move>d__2.MoveNext() in D:\Catchem-PoGo\PoGo.PokeMobBot.Logic\Navigation2.cs:line 117
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.PokeMobBot.Logic.Tasks.ForceMoveTask.<Execute>d__1.MoveNext() in D:\Catchem-PoGo\PoGo.PokeMobBot.Logic\Tasks\ForceMoveTask.cs:line 41
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.PokeMobBot.Logic.Tasks.FarmPokeStopsDiscoveryTask.<Execute>d__1.MoveNext() in D:\Catchem-PoGo\PoGo.PokeMobBot.Logic\Tasks\FarmPokestopsDiscoveryTask.cs:line 100
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.PokeMobBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in D:\Catchem-PoGo\PoGo.PokeMobBot.Logic\State\FarmState.cs:line 59
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.PokeMobBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in D:\Catchem-PoGo\PoGo.PokeMobBot.Logic\State\StateMachine.cs:line 38

anyone knows what issue is this?

**Comment by Lunat1q** [comment]
well, that can happen, but sooooo rare, anyway, fixed
